import fs from "fs/promises";
import path from "path";

export async function generatePlaywright(data: any[], cfg: any) {
  const dir = path.join(cfg.outputDir, "tests", "fixtures");
  await fs.mkdir(dir, { recursive: true });
  const content =
`// Auto-generated by Domtree Fixture Foundry
export type ${capitalize(cfg.datasetName)} = typeof data[number];
export const data = ${JSON.stringify(data, null, 2)} as const;
`;
  await fs.writeFile(path.join(dir, `${cfg.datasetName}.ts`), content);
}

function capitalize(s: string){ return s.charAt(0).toUpperCase()+s.slice(1); }
